package migrate

// Generated code, do not edit.

var DialectPostgreSQL = Migrations{
	{
		ID:         "0",
		Dialect:    "postgresql",
		Stage:      "pre",
		Statements: []string{"CREATE COLLATION IF NOT EXISTS utf8mb4_unicode_ci (provider = icu, locale = 'en_US.utf8', deterministic = true);"},
	},
	{
		ID:         "1",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS albums_users (\n  uid bytea NOT NULL,\n  user_uid bytea NOT NULL,\n  team_uid bytea DEFAULT NULL,\n  perm bigint DEFAULT NULL,\n  PRIMARY KEY (uid,user_uid));", "CREATE INDEX IF NOT EXISTS idx_albums_users_user_uid on albums_users (user_uid);", "CREATE INDEX IF NOT EXISTS idx_albums_users_team_uid on albums_users (team_uid);"},
	},
	{
		ID:         "10",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS countries (\n  id bytea NOT NULL,\n  country_slug bytea DEFAULT NULL UNIQUE,\n  country_name varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  country_description varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  country_notes varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  country_photo_id bigint DEFAULT NULL,\n  PRIMARY KEY (id)\n);", "CREATE INDEX IF NOT EXISTS uix_countries_country_slug on countries (country_slug);"},
	},
	{
		ID:         "11",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS details (\n  photo_id SERIAL NOT NULL,\n  keywords varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  keywords_src bytea DEFAULT NULL,\n  notes varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  notes_src bytea DEFAULT NULL,\n  subject varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  subject_src bytea DEFAULT NULL,\n  artist varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  artist_src bytea DEFAULT NULL,\n  copyright varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  copyright_src bytea DEFAULT NULL,\n  license varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  license_src bytea DEFAULT NULL,\n  software varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  software_src bytea DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (photo_id)\n);"},
	},
	{
		ID:         "12",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS duplicates (\n  file_name bytea NOT NULL,\n  file_root bytea NOT NULL DEFAULT '/',\n  file_hash bytea DEFAULT '',\n  file_size bigint DEFAULT NULL,\n  mod_time bigint DEFAULT NULL,\n  PRIMARY KEY (file_name,file_root));", "CREATE INDEX IF NOT EXISTS idx_duplicates_file_hash on duplicates (file_hash);"},
	},
	{
		ID:         "13",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS errors (\n  id SERIAL NOT NULL,\n  error_time timestamp DEFAULT NULL,\n  error_level bytea DEFAULT NULL,\n  error_message bytea DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS idx_errors_error_time on errors (error_time);"},
	},
	{
		ID:         "14",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS faces (\n  id bytea NOT NULL,\n  face_src bytea DEFAULT NULL,\n  face_kind int DEFAULT NULL,\n  face_hidden boolean DEFAULT NULL,\n  subj_uid bytea DEFAULT '',\n  samples int DEFAULT NULL,\n  sample_radius double precision DEFAULT NULL,\n  collisions int DEFAULT NULL,\n  collision_radius double precision DEFAULT NULL,\n  embedding_json bytea DEFAULT NULL,\n  matched_at timestamp DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS idx_faces_subj_uid on faces (subj_uid);"},
	},
	{
		ID:         "15",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS files (\n  id SERIAL NOT NULL,\n  photo_id bigint DEFAULT NULL,\n  photo_uid bytea DEFAULT NULL,\n  photo_taken_at timestamp DEFAULT NULL,\n  time_index bytea DEFAULT NULL UNIQUE,\n  media_id bytea DEFAULT NULL UNIQUE,\n  media_utc bigint DEFAULT NULL,\n  instance_id bytea DEFAULT NULL,\n  file_uid bytea DEFAULT NULL UNIQUE,\n  file_name varchar(1024) DEFAULT NULL,\n  file_root varchar(1024) DEFAULT '/',\n  original_name bytea DEFAULT NULL,\n  file_hash bytea DEFAULT NULL,\n  file_size bigint DEFAULT NULL,\n  file_codec bytea DEFAULT NULL,\n  file_type bytea DEFAULT NULL,\n  media_type bytea DEFAULT NULL,\n  file_mime bytea DEFAULT NULL,\n  file_primary boolean DEFAULT NULL,\n  file_sidecar boolean DEFAULT NULL,\n  file_missing boolean DEFAULT NULL,\n  file_portrait boolean DEFAULT NULL,\n  file_video boolean DEFAULT NULL,\n  file_duration bigint DEFAULT NULL,\n  file_fps double precision DEFAULT NULL,\n  file_frames int DEFAULT NULL,\n  file_width int DEFAULT NULL,\n  file_height int DEFAULT NULL,\n  file_orientation int DEFAULT NULL,\n  file_orientation_src bytea DEFAULT NULL,\n  file_projection bytea DEFAULT NULL,\n  file_aspect_ratio real DEFAULT NULL,\n  file_hdr boolean DEFAULT NULL,\n  file_watermark boolean DEFAULT NULL,\n  file_color_profile bytea DEFAULT NULL,\n  file_main_color bytea DEFAULT NULL,\n  file_colors bytea DEFAULT NULL,\n  file_luminance bytea DEFAULT NULL,\n  file_diff int DEFAULT -1,\n  file_chroma smallint DEFAULT -1,\n  file_software varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  file_error bytea DEFAULT NULL,\n  file_embedding real[] DEFAULT NULL,\n  mod_time bigint DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  created_in bigint DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  updated_in bigint DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  published_at timestamp DEFAULT NULL,\n  UNIQUE (file_name,file_root),\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS uix_files_file_uid on files (file_uid);", "CREATE INDEX IF NOT EXISTS idx_files_name_root on files (file_name,file_root);", "CREATE INDEX IF NOT EXISTS idx_files_search_media on files (media_id);", "CREATE INDEX IF NOT EXISTS idx_files_search_timeline on files (time_index);", "CREATE INDEX IF NOT EXISTS idx_files_instance_id on files (instance_id);", "CREATE INDEX IF NOT EXISTS idx_files_file_hash on files (file_hash);", "CREATE INDEX IF NOT EXISTS idx_files_file_main_color on files (file_main_color);", "CREATE INDEX IF NOT EXISTS idx_files_deleted_at on files (deleted_at);", "CREATE INDEX IF NOT EXISTS idx_files_photo_id on files (photo_id,file_primary);", "CREATE INDEX IF NOT EXISTS idx_files_photo_uid on files (photo_uid);", "CREATE INDEX IF NOT EXISTS idx_files_photo_taken_at on files (photo_taken_at);", "CREATE INDEX IF NOT EXISTS idx_files_media_utc on files (media_utc);", "CREATE INDEX IF NOT EXISTS idx_files_missing_root on files (file_missing,file_root);", "CREATE INDEX IF NOT EXISTS idx_files_published_at on files (published_at);"},
	},
	{
		ID:         "16",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS files_share (\n  file_id SERIAL NOT NULL,\n  service_id SERIAL NOT NULL,\n  remote_name bytea NOT NULL,\n  status bytea DEFAULT NULL,\n  error bytea DEFAULT NULL,\n  errors int DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (file_id,service_id,remote_name)\n);"},
	},
	{
		ID:         "17",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS files_sync (\n  remote_name bytea NOT NULL,\n  service_id SERIAL NOT NULL,\n  file_id bigint DEFAULT NULL,\n  remote_date timestamp DEFAULT NULL,\n  remote_size bigint DEFAULT NULL,\n  status bytea DEFAULT NULL,\n  error bytea DEFAULT NULL,\n  errors int DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (remote_name,service_id));", "CREATE INDEX IF NOT EXISTS idx_files_sync_file_id on files_sync (file_id);"},
	},
	{
		ID:         "18",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS folders (\n  path bytea DEFAULT NULL,\n  root bytea DEFAULT '',\n  folder_uid bytea NOT NULL,\n  folder_type bytea DEFAULT NULL,\n  folder_title varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  folder_category varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  folder_description varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  folder_order bytea DEFAULT NULL,\n  folder_country bytea DEFAULT 'zz',\n  folder_year int DEFAULT NULL,\n  folder_month int DEFAULT NULL,\n  folder_day int DEFAULT NULL,\n  folder_favorite boolean DEFAULT NULL,\n  folder_private boolean DEFAULT NULL,\n  folder_ignore boolean DEFAULT NULL,\n  folder_watch boolean DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  modified_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  published_at timestamp DEFAULT NULL,\n  UNIQUE (path, root),\n  PRIMARY KEY (folder_uid));", "CREATE INDEX IF NOT EXISTS idx_folders_path_root on folders (path,root);", "CREATE INDEX IF NOT EXISTS idx_folders_folder_category on folders (folder_category);", "CREATE INDEX IF NOT EXISTS idx_folders_country_year_month on folders (folder_country,folder_year,folder_month);", "CREATE INDEX IF NOT EXISTS idx_folders_deleted_at on folders (deleted_at);", "CREATE INDEX IF NOT EXISTS idx_folders_published_at on folders (published_at);"},
	},
	{
		ID:         "19",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS keywords (\n  id SERIAL NOT NULL,\n  keyword varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  skip boolean DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS idx_keywords_keyword on keywords (keyword);"},
	},
	{
		ID:         "2",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS auth_sessions (\n  id bytea NOT NULL,\n  client_ip varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  user_uid bytea DEFAULT '',\n  user_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  auth_provider bytea DEFAULT '',\n  auth_method bytea DEFAULT '',\n  auth_domain bytea DEFAULT '',\n  auth_id bytea DEFAULT '',\n  auth_scope varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT '',\n  last_active bigint DEFAULT NULL,\n  sess_expires bigint DEFAULT NULL,\n  sess_timeout bigint DEFAULT NULL,\n  preview_token bytea DEFAULT '',\n  download_token bytea DEFAULT '',\n  access_token bytea DEFAULT '',\n  refresh_token bytea DEFAULT '',\n  id_token bytea DEFAULT '',\n  user_agent varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  data_json bytea DEFAULT NULL,\n  ref_id bytea DEFAULT '',\n  login_ip varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  login_at timestamp DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS idx_auth_sessions_client_ip on auth_sessions (client_ip);", "CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_uid on auth_sessions (user_uid);", "CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_name on auth_sessions (user_name);", "CREATE INDEX IF NOT EXISTS idx_auth_sessions_auth_id on auth_sessions (auth_id);", "CREATE INDEX IF NOT EXISTS idx_auth_sessions_sess_expires on auth_sessions (sess_expires);"},
	},
	{
		ID:         "20",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS labels (\n  id SERIAL NOT NULL,\n  label_uid bytea DEFAULT NULL UNIQUE,\n  label_slug bytea DEFAULT NULL UNIQUE,\n  custom_slug bytea DEFAULT NULL,\n  label_name varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  label_priority int DEFAULT NULL,\n  label_favorite boolean DEFAULT NULL,\n  label_description varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  label_notes varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  photo_count int DEFAULT 1,\n  thumb bytea DEFAULT '',\n  thumb_src bytea DEFAULT '',\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  published_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS uix_labels_label_slug on labels (label_slug);", "CREATE INDEX IF NOT EXISTS uix_labels_label_uid on labels (label_uid);", "CREATE INDEX IF NOT EXISTS idx_labels_custom_slug on labels (custom_slug);", "CREATE INDEX IF NOT EXISTS idx_labels_thumb on labels (thumb);", "CREATE INDEX IF NOT EXISTS idx_labels_deleted_at on labels (deleted_at);", "CREATE INDEX IF NOT EXISTS idx_labels_published_at on labels (published_at);"},
	},
	{
		ID:         "21",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS lenses (\n  id SERIAL NOT NULL,\n  lens_slug bytea DEFAULT NULL UNIQUE,\n  lens_name varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  lens_make varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  lens_model varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  lens_type varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  lens_description varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  lens_notes varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS uix_lenses_lens_slug on lenses (lens_slug);", "CREATE INDEX IF NOT EXISTS idx_lenses_deleted_at on lenses (deleted_at);"},
	},
	{
		ID:         "22",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS links (\n  link_uid bytea NOT NULL,\n  share_uid bytea DEFAULT NULL,\n  share_slug bytea DEFAULT NULL,\n  link_token bytea DEFAULT NULL,\n  link_expires int DEFAULT NULL,\n  link_views bigint DEFAULT NULL,\n  max_views bigint DEFAULT NULL,\n  has_password boolean DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  modified_at timestamp DEFAULT NULL,\n  comment varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  perm bigint DEFAULT NULL,\n  ref_id bytea DEFAULT NULL,\n  created_by bytea DEFAULT NULL,\n  UNIQUE (share_uid, link_token),\n  PRIMARY KEY (link_uid));", "CREATE INDEX IF NOT EXISTS idx_links_uid_token on links (share_uid,link_token);", "CREATE INDEX IF NOT EXISTS idx_links_share_slug on links (share_slug);", "CREATE INDEX IF NOT EXISTS idx_links_created_by on links (created_by);"},
	},
	{
		ID:         "23",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS markers (\n  marker_uid bytea NOT NULL,\n  file_uid bytea DEFAULT '',\n  marker_type bytea DEFAULT '',\n  marker_src bytea DEFAULT '',\n  marker_name varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  marker_review boolean DEFAULT NULL,\n  marker_invalid boolean DEFAULT NULL,\n  subj_uid bytea DEFAULT NULL,\n  subj_src bytea DEFAULT '',\n  face_id bytea DEFAULT NULL,\n  face_dist double precision DEFAULT -1,\n  embeddings_json bytea DEFAULT NULL,\n  landmarks_json bytea DEFAULT NULL,\n  x real DEFAULT NULL,\n  y real DEFAULT NULL,\n  w real DEFAULT NULL,\n  h real DEFAULT NULL,\n  q int DEFAULT NULL,\n  size int DEFAULT -1,\n  score smallint DEFAULT NULL,\n  thumb bytea DEFAULT '',\n  matched_at timestamp DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (marker_uid));", "CREATE INDEX IF NOT EXISTS idx_markers_file_uid on markers (file_uid);", "CREATE INDEX IF NOT EXISTS idx_markers_subj_uid_src on markers (subj_uid,subj_src);", "CREATE INDEX IF NOT EXISTS idx_markers_face_id on markers (face_id);", "CREATE INDEX IF NOT EXISTS idx_markers_thumb on markers (thumb);", "CREATE INDEX IF NOT EXISTS idx_markers_matched_at on markers (matched_at);"},
	},
	{
		ID:         "24",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS migrations (\n  id varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,\n  dialect varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  error varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  source varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  started_at timestamp DEFAULT NULL,\n  finished_at timestamp DEFAULT NULL,\n  stage varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  PRIMARY KEY (id)\n);"},
	},
	{
		ID:         "25",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS passwords (\n  uid bytea NOT NULL,\n  hash bytea DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (uid)\n);"},
	},
	{
		ID:         "26",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS photos (\n  id SERIAL NOT NULL,\n  uuid bytea DEFAULT NULL,\n  taken_at timestamp DEFAULT NULL,\n  taken_at_local timestamp DEFAULT NULL,\n  taken_src bytea DEFAULT NULL,\n  photo_uid bytea DEFAULT NULL UNIQUE,\n  photo_type bytea DEFAULT 'image',\n  type_src bytea DEFAULT NULL,\n  photo_title varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  title_src bytea DEFAULT NULL,\n  photo_description varchar(4096) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  description_src bytea DEFAULT NULL,\n  photo_path bytea DEFAULT NULL,\n  photo_name bytea DEFAULT NULL,\n  original_name bytea DEFAULT NULL,\n  photo_stack smallint DEFAULT NULL,\n  photo_favorite boolean DEFAULT NULL,\n  photo_private boolean DEFAULT NULL,\n  photo_scan boolean DEFAULT NULL,\n  photo_panorama boolean DEFAULT NULL,\n  time_zone bytea DEFAULT NULL,\n  place_id bytea DEFAULT 'zz',\n  place_src bytea DEFAULT NULL,\n  cell_id bytea DEFAULT 'zz',\n  cell_accuracy int DEFAULT NULL,\n  photo_altitude int DEFAULT NULL,\n  photo_lat real DEFAULT NULL,\n  photo_lng real DEFAULT NULL,\n  photo_country bytea DEFAULT 'zz',\n  photo_year int DEFAULT NULL,\n  photo_month int DEFAULT NULL,\n  photo_day int DEFAULT NULL,\n  photo_iso int DEFAULT NULL,\n  photo_exposure bytea DEFAULT NULL,\n  photo_f_number real DEFAULT NULL,\n  photo_focal_length int DEFAULT NULL,\n  photo_quality smallint DEFAULT NULL,\n  photo_faces int DEFAULT NULL,\n  photo_resolution smallint DEFAULT NULL,\n  photo_color smallint DEFAULT -1,\n  camera_id bigint DEFAULT 1,\n  camera_serial bytea DEFAULT NULL,\n  camera_src bytea DEFAULT NULL,\n  lens_id bigint DEFAULT 1,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  edited_at timestamp DEFAULT NULL,\n  checked_at timestamp DEFAULT NULL,\n  estimated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  photo_duration bigint DEFAULT NULL,\n  created_by bytea DEFAULT NULL,\n  published_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS uix_photos_photo_uid on photos (photo_uid);", "CREATE INDEX IF NOT EXISTS idx_photos_path_name on photos (photo_path,photo_name);", "CREATE INDEX IF NOT EXISTS idx_photos_cell_id on photos (cell_id);", "CREATE INDEX IF NOT EXISTS idx_photos_photo_lat on photos (photo_lat);", "CREATE INDEX IF NOT EXISTS idx_photos_photo_lng on photos (photo_lng);", "CREATE INDEX IF NOT EXISTS idx_photos_country_year_month on photos (photo_country,photo_year,photo_month);", "CREATE INDEX IF NOT EXISTS idx_photos_camera_lens on photos (camera_id,lens_id);", "CREATE INDEX IF NOT EXISTS idx_photos_uuid on photos (uuid);", "CREATE INDEX IF NOT EXISTS idx_photos_taken_uid on photos (taken_at,photo_uid);", "CREATE INDEX IF NOT EXISTS idx_photos_checked_at on photos (checked_at);", "CREATE INDEX IF NOT EXISTS idx_photos_deleted_at on photos (deleted_at);", "CREATE INDEX IF NOT EXISTS idx_photos_place_id on photos (place_id);", "CREATE INDEX IF NOT EXISTS idx_photos_ymd on photos (photo_day);", "CREATE INDEX IF NOT EXISTS idx_photos_created_by on photos (created_by);", "CREATE INDEX IF NOT EXISTS idx_photos_published_at on photos (published_at);"},
	},
	{
		ID:         "27",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS photos_albums (\n  photo_uid bytea NOT NULL,\n  album_uid bytea NOT NULL,\n  \"order\" int DEFAULT NULL,\n  hidden boolean DEFAULT NULL,\n  missing boolean DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (photo_uid,album_uid));", "CREATE INDEX IF NOT EXISTS idx_photos_albums_album_uid on photos_albums (album_uid);"},
	},
	{
		ID:         "28",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS photos_keywords (\n  photo_id SERIAL NOT NULL,\n  keyword_id SERIAL NOT NULL,\n  PRIMARY KEY (photo_id,keyword_id));", "CREATE INDEX IF NOT EXISTS idx_photos_keywords_keyword_id on photos_keywords (keyword_id);"},
	},
	{
		ID:         "29",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS photos_labels (\n  photo_id SERIAL NOT NULL,\n  label_id SERIAL NOT NULL,\n  label_src bytea DEFAULT NULL,\n  uncertainty smallint DEFAULT NULL,\n  PRIMARY KEY (photo_id,label_id));", "CREATE INDEX IF NOT EXISTS idx_photos_labels_label_id on photos_labels (label_id);"},
	},
	{
		ID:         "3",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS auth_users (\n  id int NOT NULL,\n  user_uuid bytea DEFAULT NULL,\n  user_uid bytea DEFAULT NULL UNIQUE,\n  auth_provider bytea DEFAULT '',\n  auth_id bytea DEFAULT '',\n  user_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  display_name varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  user_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  backup_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  user_role varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',\n  user_attr varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  super_admin boolean DEFAULT NULL,\n  can_login boolean DEFAULT NULL,\n  login_at timestamp DEFAULT NULL,\n  expires_at timestamp DEFAULT NULL,\n  webdav boolean DEFAULT NULL,\n  base_path bytea DEFAULT NULL,\n  upload_path bytea DEFAULT NULL,\n  can_invite boolean DEFAULT NULL,\n  invite_token bytea DEFAULT NULL,\n  invited_by varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  verify_token bytea DEFAULT NULL,\n  verified_at timestamp DEFAULT NULL,\n  consent_at timestamp DEFAULT NULL,\n  born_at timestamp DEFAULT NULL,\n  reset_token bytea DEFAULT NULL,\n  preview_token bytea DEFAULT NULL,\n  download_token bytea DEFAULT NULL,\n  thumb bytea DEFAULT '',\n  thumb_src bytea DEFAULT '',\n  ref_id bytea DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS uix_auth_users_user_uid on auth_users (user_uid);", "CREATE INDEX IF NOT EXISTS idx_auth_users_user_uuid on auth_users (user_uuid);", "CREATE INDEX IF NOT EXISTS idx_auth_users_user_email on auth_users (user_email);", "CREATE INDEX IF NOT EXISTS idx_auth_users_expires_at on auth_users (expires_at);", "CREATE INDEX IF NOT EXISTS idx_auth_users_born_at on auth_users (born_at);", "CREATE INDEX IF NOT EXISTS idx_auth_users_deleted_at on auth_users (deleted_at);", "CREATE INDEX IF NOT EXISTS idx_auth_users_auth_id on auth_users (auth_id);", "CREATE INDEX IF NOT EXISTS idx_auth_users_user_name on auth_users (user_name);", "CREATE INDEX IF NOT EXISTS idx_auth_users_invite_token on auth_users (invite_token);", "CREATE INDEX IF NOT EXISTS idx_auth_users_thumb on auth_users (thumb);"},
	},
	{
		ID:         "30",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS photos_users (\n  uid bytea NOT NULL,\n  user_uid bytea NOT NULL,\n  team_uid bytea DEFAULT NULL,\n  perm bigint DEFAULT NULL,\n  PRIMARY KEY (uid,user_uid));", "CREATE INDEX IF NOT EXISTS idx_photos_users_team_uid on photos_users (team_uid);", "CREATE INDEX IF NOT EXISTS idx_photos_users_user_uid on photos_users (user_uid);"},
	},
	{
		ID:         "31",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS places (\n  id bytea NOT NULL,\n  place_label varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  place_district varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  place_city varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  place_state varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  place_country bytea DEFAULT NULL,\n  place_keywords varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  place_favorite boolean DEFAULT NULL,\n  photo_count int DEFAULT 1,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS idx_places_place_district on places (place_district);", "CREATE INDEX IF NOT EXISTS idx_places_place_city on places (place_city);", "CREATE INDEX IF NOT EXISTS idx_places_place_state on places (place_state);"},
	},
	{
		ID:         "32",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS reactions (\n  uid bytea NOT NULL,\n  user_uid bytea NOT NULL,\n  reaction bytea NOT NULL,\n  reacted int DEFAULT NULL,\n  reacted_at timestamp DEFAULT NULL,\n  PRIMARY KEY (uid,user_uid,reaction));", "CREATE INDEX IF NOT EXISTS idx_reactions_reacted_at on reactions (reacted_at);"},
	},
	{
		ID:         "33",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS services (\n  id SERIAL NOT NULL,\n  acc_name varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  acc_owner varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  acc_url varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  acc_type bytea DEFAULT NULL,\n  acc_key bytea DEFAULT NULL,\n  acc_user bytea DEFAULT NULL,\n  acc_pass bytea DEFAULT NULL,\n  acc_timeout bytea DEFAULT NULL,\n  acc_error bytea DEFAULT NULL,\n  acc_errors int DEFAULT NULL,\n  acc_share boolean DEFAULT NULL,\n  acc_sync boolean DEFAULT NULL,\n  retry_limit int DEFAULT NULL,\n  share_path bytea DEFAULT NULL,\n  share_size bytea DEFAULT NULL,\n  share_expires int DEFAULT NULL,\n  sync_path bytea DEFAULT NULL,\n  sync_status bytea DEFAULT NULL,\n  sync_interval int DEFAULT NULL,\n  sync_date timestamp DEFAULT NULL,\n  sync_upload boolean DEFAULT NULL,\n  sync_download boolean DEFAULT NULL,\n  sync_filenames boolean DEFAULT NULL,\n  sync_raw boolean DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS idx_accounts_deleted_at on services (deleted_at);", "CREATE INDEX IF NOT EXISTS idx_services_deleted_at on services (deleted_at);"},
	},
	{
		ID:         "34",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS subjects (\n  subj_uid bytea NOT NULL,\n  subj_type bytea DEFAULT '',\n  subj_src bytea DEFAULT '',\n  subj_slug bytea DEFAULT '',\n  subj_name varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT '' UNIQUE,\n  subj_alias varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT '',\n  subj_bio varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  subj_notes varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  subj_favorite boolean DEFAULT false,\n  subj_hidden boolean DEFAULT false,\n  subj_private boolean DEFAULT false,\n  subj_excluded boolean DEFAULT true,\n  file_count int DEFAULT 0,\n  photo_count int DEFAULT 0,\n  thumb bytea DEFAULT '',\n  thumb_src bytea DEFAULT '',\n  metadata_json bytea DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  PRIMARY KEY (subj_uid));", "CREATE INDEX IF NOT EXISTS uix_subjects_subj_name on subjects (subj_name);", "CREATE INDEX IF NOT EXISTS idx_subjects_subj_slug on subjects (subj_slug);", "CREATE INDEX IF NOT EXISTS idx_subjects_thumb on subjects (thumb);", "CREATE INDEX IF NOT EXISTS idx_subjects_deleted_at on subjects (deleted_at);"},
	},
	{
		ID:         "35",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS users (\n  id int NOT NULL,\n  address_id int DEFAULT 1,\n  user_uid bytea DEFAULT NULL UNIQUE,\n  mother_uid bytea DEFAULT NULL,\n  father_uid bytea DEFAULT NULL,\n  global_uid bytea DEFAULT NULL,\n  full_name varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  nick_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  maiden_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  artist_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  user_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  user_status varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  user_disabled boolean DEFAULT NULL,\n  user_settings text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  primary_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  email_confirmed boolean DEFAULT NULL,\n  backup_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  person_url bytea DEFAULT NULL,\n  person_phone varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  person_status varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  person_avatar bytea DEFAULT NULL,\n  person_location varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  person_bio text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  person_accounts text COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  business_url bytea DEFAULT NULL,\n  business_phone varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  business_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  company_name varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  department_name varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  job_title varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  birth_year int DEFAULT NULL,\n  birth_month int DEFAULT NULL,\n  birth_day int DEFAULT NULL,\n  terms_accepted boolean DEFAULT NULL,\n  is_artist boolean DEFAULT NULL,\n  is_subject boolean DEFAULT NULL,\n  role_admin boolean DEFAULT NULL,\n  role_guest boolean DEFAULT NULL,\n  role_child boolean DEFAULT NULL,\n  role_family boolean DEFAULT NULL,\n  role_friend boolean DEFAULT NULL,\n  webdav boolean DEFAULT NULL,\n  storage_path bytea DEFAULT NULL,\n  can_invite boolean DEFAULT NULL,\n  invite_token bytea DEFAULT NULL,\n  invited_by bytea DEFAULT NULL,\n  confirm_token bytea DEFAULT NULL,\n  reset_token bytea DEFAULT NULL,\n  api_token bytea DEFAULT NULL,\n  api_secret bytea DEFAULT NULL,\n  login_attempts int DEFAULT NULL,\n  login_at timestamp DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS uix_users_user_uid on users (user_uid);", "CREATE INDEX IF NOT EXISTS idx_users_global_uid on users (global_uid);", "CREATE INDEX IF NOT EXISTS idx_users_primary_email on users (primary_email);", "CREATE INDEX IF NOT EXISTS idx_users_deleted_at on users (deleted_at);"},
	},
	{
		ID:         "36",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS albums (\n  id SERIAL NOT NULL,\n  album_uid bytea DEFAULT NULL UNIQUE,\n  parent_uid bytea DEFAULT '',\n  album_slug bytea DEFAULT NULL,\n  album_path bytea DEFAULT NULL,\n  album_type bytea DEFAULT 'album',\n  album_title varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  album_location varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  album_category varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  album_caption varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  album_description varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  album_notes varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  album_filter bytea DEFAULT '',\n  album_order bytea DEFAULT NULL,\n  album_template bytea DEFAULT NULL,\n  album_state varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  album_country bytea DEFAULT 'zz',\n  album_year int DEFAULT NULL,\n  album_month int DEFAULT NULL,\n  album_day int DEFAULT NULL,\n  album_favorite boolean DEFAULT NULL,\n  album_private boolean DEFAULT NULL,\n  thumb bytea DEFAULT '',\n  thumb_src bytea DEFAULT '',\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  created_by bytea DEFAULT NULL,\n  published_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS uix_albums_album_uid on albums (album_uid);", "CREATE INDEX IF NOT EXISTS idx_albums_album_slug on albums (album_slug);", "CREATE INDEX IF NOT EXISTS idx_albums_album_path on albums (album_path);", "CREATE INDEX IF NOT EXISTS idx_albums_album_title on albums (album_title);", "CREATE INDEX IF NOT EXISTS idx_albums_deleted_at on albums (deleted_at);", "CREATE INDEX IF NOT EXISTS idx_albums_album_category on albums (album_category);", "CREATE INDEX IF NOT EXISTS idx_albums_album_state on albums (album_state);", "CREATE INDEX IF NOT EXISTS idx_albums_country_year_month on albums (album_country,album_year,album_month);", "CREATE INDEX IF NOT EXISTS idx_albums_ymd on albums (album_day);", "CREATE INDEX IF NOT EXISTS idx_albums_thumb on albums (thumb);", "CREATE INDEX IF NOT EXISTS idx_albums_album_filter on albums (album_filter);", "CREATE INDEX IF NOT EXISTS idx_albums_created_by on albums (created_by);", "CREATE INDEX IF NOT EXISTS idx_albums_published_at on albums (published_at);"},
	},
	{
		ID:         "4",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS auth_users_details (\n  user_uid bytea NOT NULL,\n  subj_uid bytea DEFAULT NULL,\n  subj_src bytea DEFAULT '',\n  place_id bytea DEFAULT 'zz',\n  place_src bytea DEFAULT NULL,\n  cell_id bytea DEFAULT 'zz',\n  birth_year int DEFAULT -1,\n  birth_month int DEFAULT -1,\n  birth_day int DEFAULT -1,\n  user_bio varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  user_location varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  user_country bytea DEFAULT NULL,\n  user_phone varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  site_url bytea DEFAULT NULL,\n  profile_url bytea DEFAULT NULL,\n  feed_url bytea DEFAULT NULL,\n  avatar_url bytea DEFAULT NULL,\n  user_gender varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  name_title varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  given_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  middle_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  family_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  name_suffix varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  nick_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  org_title varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  org_name varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  org_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  org_phone varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  org_url bytea DEFAULT NULL,\n  id_url bytea DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (user_uid));", "CREATE INDEX IF NOT EXISTS idx_auth_users_details_subj_uid on auth_users_details (subj_uid);", "CREATE INDEX IF NOT EXISTS idx_auth_users_details_place_id on auth_users_details (place_id);", "CREATE INDEX IF NOT EXISTS idx_auth_users_details_cell_id on auth_users_details (cell_id);"},
	},
	{
		ID:         "5",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS auth_users_settings (\n  user_uid bytea NOT NULL,\n  ui_theme bytea DEFAULT NULL,\n  ui_language bytea DEFAULT NULL,\n  ui_time_zone bytea DEFAULT NULL,\n  maps_style bytea DEFAULT NULL,\n  maps_animate int DEFAULT NULL,\n  index_path bytea DEFAULT NULL,\n  index_rescan int DEFAULT NULL,\n  import_path bytea DEFAULT NULL,\n  import_move int DEFAULT NULL,\n  upload_path bytea DEFAULT NULL,\n  default_page bytea DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (user_uid)\n);"},
	},
	{
		ID:         "6",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS auth_users_shares (\n  user_uid bytea NOT NULL,\n  share_uid bytea NOT NULL,\n  link_uid bytea DEFAULT NULL,\n  expires_at timestamp DEFAULT NULL,\n  comment varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  perm bigint DEFAULT NULL,\n  ref_id bytea DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (user_uid,share_uid));", "CREATE INDEX IF NOT EXISTS idx_auth_users_shares_expires_at on auth_users_shares (expires_at);", "CREATE INDEX IF NOT EXISTS idx_auth_users_shares_share_uid on auth_users_shares (share_uid);"},
	},
	{
		ID:         "7",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS cameras (\n  id SERIAL NOT NULL,\n  camera_slug bytea DEFAULT NULL UNIQUE,\n  camera_name varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  camera_make varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  camera_model varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  camera_type varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  camera_description varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  camera_notes varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  deleted_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id));", "CREATE INDEX IF NOT EXISTS uix_cameras_camera_slug on cameras (camera_slug);", "CREATE INDEX IF NOT EXISTS idx_cameras_deleted_at on cameras (deleted_at);"},
	},
	{
		ID:         "8",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS categories (\n  label_id SERIAL NOT NULL,\n  category_id SERIAL NOT NULL,\n  PRIMARY KEY (label_id,category_id)\n);"},
	},
	{
		ID:         "9",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE TABLE IF NOT EXISTS cells (\n  id bytea NOT NULL,\n  cell_name varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  cell_street varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  cell_postcode varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  cell_category varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\n  place_id bytea DEFAULT 'zz',\n  created_at timestamp DEFAULT NULL,\n  updated_at timestamp DEFAULT NULL,\n  PRIMARY KEY (id)\n);"},
	},
	{
		ID:         "lantern",
		Dialect:    "postgresql",
		Stage:      "main",
		Statements: []string{"CREATE EXTENSION IF NOT EXISTS lantern;", "CREATE EXTENSION IF NOT EXISTS lantern_extras;", "CREATE INDEX ON files USING hnsw(file_embedding dist_cos_ops) WITH (M=5, dim=512);", "SET enable_seqscan=off;"},
	},
}
