CREATE TABLE IF NOT EXISTS users (
  id int NOT NULL,
  address_id int DEFAULT 1,
  user_uid bytea DEFAULT NULL UNIQUE,
  mother_uid bytea DEFAULT NULL,
  father_uid bytea DEFAULT NULL,
  global_uid bytea DEFAULT NULL,
  full_name varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  nick_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  maiden_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  artist_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  user_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  user_status varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  user_disabled boolean DEFAULT NULL,
  user_settings text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  primary_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  email_confirmed boolean DEFAULT NULL,
  backup_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  person_url bytea DEFAULT NULL,
  person_phone varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  person_status varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  person_avatar bytea DEFAULT NULL,
  person_location varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  person_bio text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  person_accounts text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  business_url bytea DEFAULT NULL,
  business_phone varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  business_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  company_name varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  department_name varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  job_title varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  birth_year int DEFAULT NULL,
  birth_month int DEFAULT NULL,
  birth_day int DEFAULT NULL,
  terms_accepted boolean DEFAULT NULL,
  is_artist boolean DEFAULT NULL,
  is_subject boolean DEFAULT NULL,
  role_admin boolean DEFAULT NULL,
  role_guest boolean DEFAULT NULL,
  role_child boolean DEFAULT NULL,
  role_family boolean DEFAULT NULL,
  role_friend boolean DEFAULT NULL,
  webdav boolean DEFAULT NULL,
  storage_path bytea DEFAULT NULL,
  can_invite boolean DEFAULT NULL,
  invite_token bytea DEFAULT NULL,
  invited_by bytea DEFAULT NULL,
  confirm_token bytea DEFAULT NULL,
  reset_token bytea DEFAULT NULL,
  api_token bytea DEFAULT NULL,
  api_secret bytea DEFAULT NULL,
  login_attempts int DEFAULT NULL,
  login_at timestamp DEFAULT NULL,
  created_at timestamp DEFAULT NULL,
  updated_at timestamp DEFAULT NULL,
  deleted_at timestamp DEFAULT NULL,
  PRIMARY KEY (id));
CREATE INDEX IF NOT EXISTS uix_users_user_uid on users (user_uid);
CREATE INDEX IF NOT EXISTS idx_users_global_uid on users (global_uid);
CREATE INDEX IF NOT EXISTS idx_users_primary_email on users (primary_email);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at on users (deleted_at);
