CREATE TABLE IF NOT EXISTS auth_users_details (
  user_uid bytea NOT NULL,
  subj_uid bytea DEFAULT NULL,
  subj_src bytea DEFAULT '',
  place_id bytea DEFAULT 'zz',
  place_src bytea DEFAULT NULL,
  cell_id bytea DEFAULT 'zz',
  birth_year int DEFAULT -1,
  birth_month int DEFAULT -1,
  birth_day int DEFAULT -1,
  user_bio varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  user_location varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  user_country bytea DEFAULT NULL,
  user_phone varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  site_url bytea DEFAULT NULL,
  profile_url bytea DEFAULT NULL,
  feed_url bytea DEFAULT NULL,
  avatar_url bytea DEFAULT NULL,
  user_gender varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  name_title varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  given_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  middle_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  family_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  name_suffix varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  nick_name varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  org_title varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  org_name varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  org_email varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  org_phone varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  org_url bytea DEFAULT NULL,
  id_url bytea DEFAULT NULL,
  created_at timestamp DEFAULT NULL,
  updated_at timestamp DEFAULT NULL,
  PRIMARY KEY (user_uid));
CREATE INDEX IF NOT EXISTS idx_auth_users_details_subj_uid on auth_users_details (subj_uid);
CREATE INDEX IF NOT EXISTS idx_auth_users_details_place_id on auth_users_details (place_id);
CREATE INDEX IF NOT EXISTS idx_auth_users_details_cell_id on auth_users_details (cell_id);